apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-acs
  namespace: openshift-gitops
spec:
  clusterSets:
  - acs-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: acs-gitops
              operator: In
              values:
                - local.acs
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-acs-gitops
  namespace: openshift-gitops
spec:
  clusterSets:
  - global
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: gitops
          operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-acs-gitops
  namespace: acm-acs-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-policy-acs-gitops
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: acs-gitops
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-config-gitops-cluster
  namespace: acm-policies
spec:
  clusterConditions:
    - status: 'true'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - { key: acs-gitops, operator: In, values: local.acs }