apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: acs-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "binding-policy-acs-gitops"
policies:
  - name: policy-eso-secret-store-acs
    manifests:
      - path: manifests/eso/base/
  - name: policy-acs-bootstrap
    manifests:
      - path: manifests/acs-bootstrap/base/
  - name: policy-acs-gitops-cluster
    manifests:
      - path: manifests/gitops-cluster/base
policySets:
  - name: "gitops"
    description: "Policy for bootstrapping ACS cluster with gitops"
    policies:
      - policy-eso-secret-store-acs
      - policy-acs-bootstrap
      - policy-acs-gitops-cluster
    generatePolicySetPlacement: false
    placement:
      name: placement-policy-acs-gitops