namespace: acm-policies

resources:
- acs-placement.yaml
- acs-managedclustersetbinding.yaml
- acs-managedclusterset.yaml
- acs-gitopscluster.yaml
- acs-managedcluster-cr.yaml

generators:
- acs-policy-generator-config.yaml

patches:
  - patch: |-
      - op: replace
        path: namespace
        value: openshift-gitops
    target:
      group: GitOpsCluster
      name: acs-clusters